### PR TITLE
Next types

### PR DESCRIPTION
**Pull request by tianzhich**

### CODE REVIEW

**Comment by tianzhich** [comment]
seems we missed the state types of loading plugin

**Comment by tianzhich** [comment]
give me some time, there are still some typing issues with loading package. 

`TExtraModels` was used for that and cant be removed. 😑

**Comment by semoal** [comment]
Perfect mate, tell me it's finished

**Comment by semoal** [comment]
Taking advantage if this wip probably we should check that the update to typescript 4.0 doesnt brake anyrhing

**Comment by tianzhich** [comment]
Yep, we should create a ts-loading example, or replace the original js example. We do not need the js examples cause it just removed typings from ts.

I updated the typings about the plugin, removed the ts-ignore, and fix some related issues with the loading plugin, but there are still some issues with other plugins, we need some time to fix this. 

We can check and make sure this WIP working properly with typescript 4.0 after all typing errors fixed.

**Comment by tianzhich** [comment]
testing progress was failed cause some ts-error. But there were no errors within my workspace. Are these two ts versions between node_modules and tsdx consistent?

**Comment by semoal** [comment]
> testing progress was failed cause some ts-error. But there were no errors within my workspace. Are these two ts versions between node_modules and tsdx consistent?

Yes, they should be consistent, i'll give a try asap

**Comment by semoal** [comment]
> > testing progress was failed cause some ts-error. But there were no errors within my workspace. Are these two ts versions between node_modules and tsdx consistent?
> 
> Yes, they should be consistent, i'll give a try asap

On my localhost after:

- rm -rf node_modules package-lock.json
- npm install && npm run bootstrap && npm run build && npm run test

Only fails this test (on vscode not error is shown..):
```
FAIL test/updated.test.ts
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    test/updated.test.ts:138:14 - error TS2322: Type 'Plugin<Models<any>, {}>' is not assignable to type 'Plugin<RootModel & ExtraModels, Partial<{}>>'.
      Types of property 'onModel' are incompatible.
        Type 'ModelHook<Models<any>, {}> | undefined' is not assignable to type 'ModelHook<RootModel & ExtraModels, Partial<{}>> | undefined'.
          Type 'ModelHook<Models<any>, {}>' is not assignable to type 'ModelHook<RootModel & ExtraModels, Partial<{}>>'.
            Types of parameters 'model' and 'model' are incompatible.
              Type 'NamedModel<RootModel & ExtraModels & Partial<{}>, any, any>' is not assignable to type 'NamedModel<Models<any>, any, any>'.
                Types of property 'effects' are incompatible.
                  Type 'ModelEffects<RootModel & ExtraModels & Partial<{}>> | ModelEffectsCreator<RootModel & ExtraModels & Partial<{}>> | undefined' is not assignable to type 'ModelEffects<Models<any>> | ModelEffectsCreator<Models<any>> | undefined'.
                    Type 'ModelEffects<RootModel & ExtraModels & Partial<{}>>' is not assignable to type 'ModelEffects<Models<any>> | ModelEffectsCreator<Models<any>> | undefined'.
                      Type 'ModelEffects<RootModel & ExtraModels & Partial<{}>>' is not assignable to type 'ModelEffects<Models<any>>'.
                        Index signatures are incompatible.
                          Type 'ModelEffect<RootModel & ExtraModels & Partial<{}>>' is not assignable to type 'ModelEffect<Models<any>>'.
                            Types of parameters 'rootState' and 'rootState' are incompatible.
                              Type 'ExtractRematchStateFromModels<Models<any>>' is missing the following properties from type 'ExtractRematchStateFromModels<RootModel & ExtraModels & Partial<{}>>': count, updated

    138  		plugins: [updatedPlugin<RootModel>({ dateCreator: () => mockDate })],
         		          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I added `// @ts-ignore` after that, on my local desktop all the ci's errors appeared.

It's strange because vscode is not complaining about all this errors. 
My workspace version of vscode is equals to the node_modules, 3.9.7 version.

**Comment by tianzhich** [comment]
Strangely...

on my localhost, there were still errors when I using `npm run test`:

```
test/loading-asBoolean.test.ts:295:14 - error TS2322: Type 'Plugin<Models, ExtraModelsFromLoading<Models>>' is not assignable to type 'Plugin<Models, {}>'.
      Types of property 'onModel' are incompatible.
        Type 'ModelHook<Models, ExtraModelsFromLoading<Models>> | undefined' is not assignable to type 'ModelHook<Models, {}> | undefined'.
          Type 'ModelHook<Models, ExtraModelsFromLoading<Models>>' is not assignable to type 'ModelHook<Models, {}>'.
            Types of parameters 'rematch' and 'rematch' are incompatible.
              Type 'RematchStore<Models>' is not assignable to type 'RematchStore<Models & ExtraModelsFromLoading<Models>>'.
                Types of property 'dispatch' are incompatible.
                  Type 'RematchDispatch<Models>' is not assignable to type 'RematchDispatch<Models & ExtraModelsFromLoading<Models>>'.
                    Property 'loading' is missing in type 'Dispatch<AnyAction> & ExtractRematchDispatchersFromModels<Models>' but required in type 'ExtractRematchDispatchersFromModels<Models & ExtraModelsFromLoading<Models>>'.

    295                 plugins: [loadingPlugin()],
                                  ~~~~~~~~~~~~~~~
```

But if I test using `node_modules/tsdx/dist/index.js test ./packages/loading/test/loading-asBoolean.test.ts`, these errors disappeared. 

```
 PASS  packages/loading/test/loading-asBoolean.test.ts
  loading asBoolean
    ✓ loading.global should be 0 for normal dispatched action (4ms)
    ✓ loading.global should be 1 for a dispatched effect (1ms)
    ✓ loading.global should be 2 for two dispatched effects
    ✓ should set loading.models[name] to false (1ms)
    ✓ should change the loading.models to true
    ✓ should change the loading.models to true (double dispatch) (1ms)
    ✓ should set loading.effects[name] to object of effects (2ms)
    ✓ should change the loading.effects to true (1ms)
    ✓ should change the loading.effects to true (double dispatch)
    ✓ should capture all model and global loading for simultaneous effects (305ms)
    ✓ should configure the loading name to "foobar"
    ✓ should throw if loading name is not a string (6ms)
    ✓ should block items if not in whitelist (1ms)
    ✓ should block items if in blacklist
    ✓ should throw if whitelist is not an array (1ms)
    ✓ should throw if blacklist is not an array
    ✓ should throw if contains both a whitelist & blacklist (2ms)
    ✓ should handle "hide" if effect throws
    ✓ should trigger four actions (203ms)
    ✓ should allow the propagation of the error (1ms)
    ✓ should allow the propagation of the effect result (1ms)
    ✓ should allow the propagation of the effect reject (1ms)

Test Suites: 1 passed, 1 total
Tests:       22 passed, 22 total
Snapshots:   0 total
Time:        4.27s
Ran all test suites matching /.\/packages\/loading\/test\/loading-asBoolean.test.ts/i.
```

**Comment by tianzhich** [comment]
```
error TS2322: Type 'Plugin<Models, ExtraModelsFromLoading<Models>>' is not assignable to type 'Plugin<Models, {}>'
```

We have below inheritance: 

```typescript
type ExtraModels = ExtraModelsFromLoading<Models> & SomeotherPluginModels<Models>
```

The plugin should be inferred as `Plugin<Models, Partial<ExtraModels>>`, then the returned loadingPlugin which type was `Plugin<Models, ExtraModelsFromLoading<Models>>` can assign to it. But the error said it was inferred as `Plugin<Models, {}>`. 

image

image

**Comment by tianzhich** [comment]
> > > testing progress was failed cause some ts-error. But there were no errors within my workspace. Are these two ts versions between node_modules and tsdx consistent?
> > 
> > 
> > Yes, they should be consistent, i'll give a try asap
> 
> On my localhost after:
> 
> * rm -rf node_modules package-lock.json
> * npm install && npm run bootstrap && npm run build && npm run test
> 
> Only fails this test (on vscode error isn't shown..):
> 
> ```
> FAIL test/updated.test.ts
>   ● Test suite failed to run
> 
>     TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
>     test/updated.test.ts:138:14 - error TS2322: Type 'Plugin<Models<any>, {}>' is not assignable to type 'Plugin<RootModel & ExtraModels, Partial<{}>>'.
>       Types of property 'onModel' are incompatible.
>         Type 'ModelHook<Models<any>, {}> | undefined' is not assignable to type 'ModelHook<RootModel & ExtraModels, Partial<{}>> | undefined'.
>           Type 'ModelHook<Models<any>, {}>' is not assignable to type 'ModelHook<RootModel & ExtraModels, Partial<{}>>'.
>             Types of parameters 'model' and 'model' are incompatible.
>               Type 'NamedModel<RootModel & ExtraModels & Partial<{}>, any, any>' is not assignable to type 'NamedModel<Models<any>, any, any>'.
>                 Types of property 'effects' are incompatible.
>                   Type 'ModelEffects<RootModel & ExtraModels & Partial<{}>> | ModelEffectsCreator<RootModel & ExtraModels & Partial<{}>> | undefined' is not assignable to type 'ModelEffects<Models<any>> | ModelEffectsCreator<Models<any>> | undefined'.
>                     Type 'ModelEffects<RootModel & ExtraModels & Partial<{}>>' is not assignable to type 'ModelEffects<Models<any>> | ModelEffectsCreator<Models<any>> | undefined'.
>                       Type 'ModelEffects<RootModel & ExtraModels & Partial<{}>>' is not assignable to type 'ModelEffects<Models<any>>'.
>                         Index signatures are incompatible.
>                           Type 'ModelEffect<RootModel & ExtraModels & Partial<{}>>' is not assignable to type 'ModelEffect<Models<any>>'.
>                             Types of parameters 'rootState' and 'rootState' are incompatible.
>                               Type 'ExtractRematchStateFromModels<Models<any>>' is missing the following properties from type 'ExtractRematchStateFromModels<RootModel & ExtraModels & Partial<{}>>': count, updated
> 
>     138  		plugins: [updatedPlugin<RootModel>({ dateCreator: () => mockDate })],
>          		          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> I added `// @ts-ignore` after that, on my local desktop all the ci's errors appeared.
> 
> It's strange because vscode is not complaining about all this errors.
> My workspace version of vscode is equals to the node_modules, 3.9.7 version.

Are you sure on your localhost, there were no issues above? It seems that online GitHub ci also failed to this.

If this solved, we can fix typings of other plugins like updated you mentioned.

**Comment by semoal** [comment]
> > > > testing progress was failed cause some ts-error. But there were no errors within my workspace. Are these two ts versions between node_modules and tsdx consistent?
> > > 
> > > 
> > > Yes, they should be consistent, i'll give a try asap
> > 
> > 
> > On my localhost after:
> > 
> > * rm -rf node_modules package-lock.json
> > * npm install && npm run bootstrap && npm run build && npm run test
> > 
> > Only fails this test (on vscode error isn't shown..):
> > ```
> > FAIL test/updated.test.ts
> >   ● Test suite failed to run
> > 
> >     TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
> >     test/updated.test.ts:138:14 - error TS2322: Type 'Plugin<Models<any>, {}>' is not assignable to type 'Plugin<RootModel & ExtraModels, Partial<{}>>'.
> >       Types of property 'onModel' are incompatible.
> >         Type 'ModelHook<Models<any>, {}> | undefined' is not assignable to type 'ModelHook<RootModel & ExtraModels, Partial<{}>> | undefined'.
> >           Type 'ModelHook<Models<any>, {}>' is not assignable to type 'ModelHook<RootModel & ExtraModels, Partial<{}>>'.
> >             Types of parameters 'model' and 'model' are incompatible.
> >               Type 'NamedModel<RootModel & ExtraModels & Partial<{}>, any, any>' is not assignable to type 'NamedModel<Models<any>, any, any>'.
> >                 Types of property 'effects' are incompatible.
> >                   Type 'ModelEffects<RootModel & ExtraModels & Partial<{}>> | ModelEffectsCreator<RootModel & ExtraModels & Partial<{}>> | undefined' is not assignable to type 'ModelEffects<Models<any>> | ModelEffectsCreator<Models<any>> | undefined'.
> >                     Type 'ModelEffects<RootModel & ExtraModels & Partial<{}>>' is not assignable to type 'ModelEffects<Models<any>> | ModelEffectsCreator<Models<any>> | undefined'.
> >                       Type 'ModelEffects<RootModel & ExtraModels & Partial<{}>>' is not assignable to type 'ModelEffects<Models<any>>'.
> >                         Index signatures are incompatible.
> >                           Type 'ModelEffect<RootModel & ExtraModels & Partial<{}>>' is not assignable to type 'ModelEffect<Models<any>>'.
> >                             Types of parameters 'rootState' and 'rootState' are incompatible.
> >                               Type 'ExtractRematchStateFromModels<Models<any>>' is missing the following properties from type 'ExtractRematchStateFromModels<RootModel & ExtraModels & Partial<{}>>': count, updated
> > 
> >     138  		plugins: [updatedPlugin<RootModel>({ dateCreator: () => mockDate })],
> >          		          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > ```
> > 
> > 
> > I added `// @ts-ignore` after that, on my local desktop all the ci's errors appeared.
> > It's strange because vscode is not complaining about all this errors.
> > My workspace version of vscode is equals to the node_modules, 3.9.7 version.
> 
> Are you sure on your localhost, there were no issues with `loading-asBoolean.test.ts`? It seems that online GitHub ci also failed to this.
> 
> If this solved, we can fix typings of other plugins like updated you mentioned.

Ye just show, the errors on loading tests, my issue was lerna run test was failing on updated test, so the loading testing isn't run yet. 
When i run only the loading tests, they failed like the ci is doing.

**Comment by tianzhich** [comment]
Well, I fixed all the typing errors related to plugin `loading` and `updated`. Fortunately, there are no errors in other plugins. But you guys write too much more `ts-ignore` before so I need some extra time to resolve all of this.

I have also separated the tsconfig related to tests, so all the tests file would not be ignored by our localhost typescript env. All the errors can be found before ci progress.

**Comment by semoal** [comment]
> Well, I fixed all the typing errors related to plugin `loading` and `updated`. Fortunately, there are no errors in other plugins. But you guys write too much more `ts-ignore` before so I need some extra time to resolve all of this.
> 
> I have also separated the tsconfig related to tests, so all the tests file would not be ignored by our localhost typescript env. All the errors can be found before ci progress.

Timing is not a problem dude, you're helping us a lot. 
We must stop using ts-ignore i know, my knowledge of advanced types is limited, and @pjamrozowicz is way better, but not yours.
That's why we're eternal grateful with your work. Feel free to give me some work that i could handle, like implementing extra testing, or somethng like that!

**Comment by tianzhich** [comment]
> Timing is not a problem dude, you're helping us a lot.
> We must stop using ts-ignore i know, my knowledge of advanced types is limited, and @pjamrozowicz is way better, but not yours.
> That's why we're eternal grateful with your work. Feel free to give me some work that i could handle, like implementing extra testing, or somethng like that!

You are so welcome dude. I'm so interested in rematch. And with the progress of improving typings, I also understand the design ideas behind the rematch better.

This is my first contribution on OSS community. You also help me a lot on this progress. I am very excited and willing to do more works on this project. 

I think we can refactor the js-example using ts and create some complex examples about the usage with 2 or more plugins. We can also update the documents. But Im not as good as writing using English, maybe i could update the chinese translations.

**Comment by semoal** [comment]
> > Timing is not a problem dude, you're helping us a lot.
> > We must stop using ts-ignore i know, my knowledge of advanced types is limited, and @pjamrozowicz is way better, but not yours.
> > That's why we're eternal grateful with your work. Feel free to give me some work that i could handle, like implementing extra testing, or somethng like that!
> 
> You are so welcome dude. I'm so interested in rematch. And with the progress of improving typings, I also understand the design ideas behind the rematch better.
> 
> This is my first contribution on OSS community. You also help me a lot on this progress. I am very excited and willing to do more works on this project.
> 
> I think we can refactor the js-example using ts and create some complex examples about the usage with 2 or more plugins. We can also update the documents. But Im not as good as writing using English, maybe i could update the chinese translations.

About chinese documentation, we ended up with that because was complicated to maintain, because the actual maintainers didn't know chinese haha.

We could update the examples, and try to remove some ts-ignore that's still in the codebase.

Should we release this branch for fixing circular reference, and work in the examples on other branch?

**Comment by tianzhich** [comment]
Yeah, we can release this. After that, we have two branches, one for the work of removing ts-ignore, and another for update the examples. I can update Chinese docs on the stable release, based on your updated original documentation.

**Comment by pjamrozowicz** [comment]
Good job @tianzhich, especially on the plugins types improvements! It was hell 🔥

**Comment by tianzhich** [comment]
> Good job @tianzhich, especially on the plugins types improvements! It was hell 🔥

Thank you for your previous works, I can't handle it without these works.

It feels so good to talk and collaborate with you guys. 😃

**Pull request merged**
