### PR TITLE
Revert "WIP: Just a test"

### PR DESCRIPTION
**Pull request by ShMcK**
Reverts rematch/rematch#42

### CODE REVIEW

**Comment by blairbodnar** [comment]
Hmm, it merged. But I had "Use my admin privileges to merge" checked.

**Comment by blairbodnar** [comment]
@ShMcK Maybe the "WIP" has to be the first text in the title?

**Comment by ShMcK** [comment]
Yes, it has to be the first text.

**Comment by blairbodnar** [comment]
Ah cool, Roger that 👍

**Pull request merged**
