### PR TITLE
Fixed: links in api.md TOC

### PR DESCRIPTION
**Pull request by upupming**

### CODE REVIEW

**Comment by semoal** [comment]
Actual links are working properly, am i wrong?

**Comment by upupming** [comment]
@semoal Sorry, I'm clicking in the markdown file and then got 404.

**Comment by upupming** [comment]
But actually the first link at this page: https://rematch.github.io/rematch/#/api-reference/reduxapi?id=init-redux-api will get 404.

**Comment by semoal** [comment]
So, please, if the link that doesnt work is the first link, plz update just the first link

**Comment by upupming** [comment]
> So, please, if the link that doesnt work is the first link, plz update just the first link

Sure I will do fix in another PR.

**Pull request closed without merging**
