### PR TITLE
Attempt to fix typings

### PR DESCRIPTION
**Pull request by d3dc**
Since it seems like I've created a snafu with #483, I massaged the typings for the two plugins - `select` and `typed-state` that extend `Rematch.ModelConfig`

[I tried to do it according to the plugin recipe in the docs](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-plugin-d-ts.html).

I also removed `subscriptions`

### CODE REVIEW

**Comment by d3dc** [comment]
I'm able to get `npm run build` to run with an ambient `.d.ts` for `@rematch/select` when mapping `@rematch/core` to the local path.

The local path mapping is necessary because the published version of `core` has duplicate typings.

**Comment by ShMcK** [comment]
@d3dc I've added you as a collaborator for rematch. I hope that makes your life easier :)

**Comment by d3dc** [comment]
@ShMcK I'll see if it helps. I can fix the link in my docs now 😉.

The trick to everything was doing:
```
// a/plugins/select/tsconfig.json
 {
   "compilerOptions": {
+      "baseUrl": "./src",
       "outDir": "./lib",
       "sourceMap": true,
       "target": "es5",
       "lib": ["es2017"],
       "moduleResolution": "node",
+      "paths": {
+        "@rematch/core": ["../../../"]
+      },
   },
```

This fixes the `declare module '@rematch/core'` part and the import in the code.

I'm assuming this is because the published (`node_modules`) version does not have the typings. I guess I go ahead and try to publish?

**Comment by d3dc** [comment]
Typed-state is still not building even when I replace the build config...

**Comment by ShMcK** [comment]
Sorry, I guess we've both gone down this rabbit hole. 

@d3dc thanks for joining as a contributor. Feel free to manage and merge in any PRs related to the select plugin. I appreciate the help :)

**Comment by ShMcK** [comment]
I'm still getting an error on build.

```
[!] (rpt2 plugin) Error: rematch/plugins/select/src/index.ts(95,8): semantic error TS2349 Cannot invoke an expression whose type lacks a call signature. Type 'never' has no compatible call signatures.
```

In reference to the following typings:

```
	export interface ModelConfig<S = any, SS = S> {
		selectors?: ModelSelectorsConfig<S>,
	}
```

How did you manage to run it with just a warning?

**Comment by ShMcK** [comment]
@d3dc - would you like to be added as an npm maintainer for `@rematch/select`? If so, just send me an email with your npm username. My email should be publicly available on my Github.

**Comment by d3dc** [comment]
I think I might be wrong about why my changes get `typed-state` to compile. I Removed the `ModelConfig` interface as a sanity check, and it still built.

**Comment by ShMcK** [comment]
I finally managed to get it to build by changing the reference in the select plugin to the local build.

It should be published now as 2.0.0. Thanks again for all of your effort, this was not easy.

And again, let me know if you'd like more shared control over publishing the select plugin.

**Pull request merged**
