### PR TITLE
v1.0.0-alpha

### PR DESCRIPTION
**Pull request by ShMcK**
progress towards #239.

# Goals

1. TypeScript support
2. Support multiple stores
3. Dispatch into multiple stores with global dispatch

# Breaking Changes

1. global getState will now get state from all stores

### CODE REVIEW

**Comment by ShMcK** [comment]
I'll leave this open for a day, otherwise will merge tomorrow as v1.0.0.

**Comment by ShMcK** [comment]
Closing in favor of #254. Most of the work has already been done.

**Comment by ShMcK** [comment]
First working version.

TODO:
- [ ] slowly add skipped plugin tests back
- [ ] recover test coverage
- [ ] fix all typings for TS
- [ ] create TS demo and ensure it works
- [ ] write tests for global dispatch

**Comment by nWidart** [comment]
I started a demo here: https://github.com/nWidart/rematch-typescript

However for some reason it doesn't compile with:

```
./src/index.tsx
Module not found: Can't resolve '@rematch/core' in '/Users/nicolaswidart/Sites/Tests/rematch-typescript/src'
```

I've required rematch with `"@rematch/core": "rematch/rematch#feature/store-model",`

I'm not sure why as I've required the experimental branch before.

**Comment by ShMcK** [comment]
@nWidart I believe there wouldn't be any built version of the branch within the repo, only the source code.

There are a few options:

1) Add the TS demo to this PR under examples/typescript/demo-name
2) Add another PR, and I can cherry pick the commits over
3) Clone this branch and build it locally, then reference it using `npm link` or `file:path/to/built/rematch`

**Comment by nWidart** [comment]
Oh right, that makes sense.

I've added the example code in this pull request `examples/typescript/count` folder and built the project (build:all). The error persists though. I guess I'll wait until this PR has progressed more 😄 .

**Comment by ShMcK** [comment]
@nWidart you're right, most of the demos would likely be better suited as git submodules.

I worry though, 1.0.0 will produce several minor breaking changes. If demos are submodules, and the submodules aren't versioned the same, it will lead to some headaches. It may be easier to just put everything within the repo.

We're pretty close now.

**Comment by ShMcK** [comment]
TypeScript Question:

Plugins are merged into a single PluginFactory class - this class cannot know which properties will be added to it. How can I write typings for Plugins & the PluginFactory?

**Comment by ShMcK** [comment]
Seems like the last major blocker to 1.0.0 is the loading plugin. 
Not sure why tests are failing, it seems to be working.

**Comment by scottclayton** [comment]
I have pushed a change that resolves most loading test failures:
- there was a mutation of the count model that was being referenced in the tests—I made it a function
- the asBoolean and asNumber tests had both their configurations set to `asNumber: true`, so I extracted the config to be generated a function that has `asNumber` parameterized
- I also flipped around the `describe` text for the asBoolean and asNumber tests

There are still 4 outstanding test failiures.

**Comment by ShMcK** [comment]
I think we're ready for a 1.0.0 alpha.0

**Comment by nWidart** [comment]
Awesome job!

Is there anything to do to be able to test the typescript version? Since the example folder is a submodule.

**Comment by ShMcK** [comment]
I removed the .git module from the ts example, so it should run with the local copy of rematch. 

You can test it out with the following:

```shell
// clone this branch
cd examples/ts/scoreBoard
rm -rf node_modules
npm install
npm start
```

**Comment by nWidart** [comment]
Hm odd, I still can't see the files here: https://github.com/rematch/rematch/tree/feature/store-model/examples/ts

**Comment by ShMcK** [comment]
You're right. I hadn't noticed as it works locally. Give me a minute.

**Comment by nWidart** [comment]
Just updated my local branch, and can see the typescript contents 👍 
I'll play around with it today. 😄

**Comment by nWidart** [comment]
Getting this after having ran `yarn`, `yarn start` in the examples/typescript/count folder.

```
/Users/nicolaswidart/Sites/Tests/rematch/examples/typescript/count/node_modules/@rematch/core/typings/rematch/index.d.ts
(24,31): Generic type 'Reducer' requires 1 type argument(s).
```

In that file: 
image

Looks like it's a generic

**Comment by ShMcK** [comment]
I removed the dependency on "redux" from the ts example package.json and it now works.

Currently, Rematch relies on Redux@4.0.0-beta.2. The 4.x branch is aimed at cleaning up overly complex Redux typings that require generics for nearly everything.

**Comment by ShMcK** [comment]
closes #239, closes #244, closes #306, closes #320.

Will merge and release v1.0.0.alpha.0 later today if no objections.

v0 branch is preserved.

**Comment by nWidart** [comment]
Nice, that removed the redux related error.
It's still throwing `Uncaught (in promise) TypeError: Cannot read property 'exposed' of undefined` when clicking the + button though.

**Comment by ShMcK** [comment]
Strange. I wonder why I don't receive the same errors. The demo is fully functional.

Is there anywhere our configurations may be different?

**Comment by nWidart** [comment]
Hm odd. Maybe I need to re-build something on the parent, the package itself?

**Comment by ShMcK** [comment]
You'll have to run `npm run build` in the root. It may require `npm run install:all` first.

I'll test with `yarn` as I've been primarily using `npm` to see if there is a difference.

**Comment by nWidart** [comment]
the `install:all` command threw a lot of errors/warnings. Stuff like

```
src/index.ts(26,3): error TS2322: Type '{ config: { redux: { combineReducers: (reducers: ReducersMapObject) => Reducer<{}>; }; }; }' is not assignable to type 'Plugin'.
  Object literal may only specify known properties, and 'config' does not exist in type 'Plugin'.
```

After building, and restarting the ts/count example, the error remains. I'll try with npm I guess 😄

**Comment by ShMcK** [comment]
Same issue here. Though config does exist on Plugin.

```js
export interface Plugin {
  config?: InitConfig,
 ....
}
```

**Comment by ShMcK** [comment]
Ah, it seems plugins are referencing the older version of @rematch/core.

**Comment by nWidart** [comment]
Updated my fork, install:all doesn't show the same errors, now those : https://gist.github.com/nWidart/f55cf2dd79bb0e4b5cb67e6c0c339723 (this is part of the full output).

But, after re-running the ts example, it works now! 🎉

**Pull request merged**
