### PR TITLE
Plugin for type-checking state

### PR DESCRIPTION
**Pull request by koss-lebedev**
Hey @ShMcK ,

I really like the idea you outlined in https://github.com/rematch/rematch/issues/221, so I started implementing it as a plugin. I wanted to submit PR early so that you could weigh in on things you don't like or disagree on.

First of all, I don't think it's possible to check state against TypeScript or Flow definitions since those are tools for static type checking and they won't be available at runtime. It would be super cool to be able to reuse TS/Flow definitions, but it simply won't work here.

So the next best thing I think we can do is to have our own type definitions that use syntax similar to that of Flow or TS. I know that `mobx-state-tree` uses custom API like this:

```js
const Todo = types.model({
    title: types.string
})
```

However, in our case, I don't think it's necessary, and simple string-based syntax definition will do just fine. So this is the example of how definitions can look like:

```js
typings: {
    name: 'string',
    age: 'number',
    height: 'number?',
    isDeveloper: 'boolean',
    birthDate: 'date|number',
    address: {
      country: 'string?',
      city: 'string',
    }
  }
```

It would support primitive types like `string` and `number`, union types like `string|number` which would be valid if the value is either `string` or `number`, and optional types like `string?` which is essentially equal to `string|undefined`.

### CODE REVIEW

**Comment by ShMcK** [comment]
@koss-lebedev thanks for taking up the cause :)

Is there a schema validation library you were thinking of using for this? 

Validating types can be a can of worms once you dive into it, consider deeply nested objects, arrays with multiple types, immutable data structures, etc. Somebody's done the work for you.

**Comment by koss-lebedev** [comment]
@ShMcK Thanks for your input! I actually agree with you that we should use ready solution for typechecking instead of reinventing it as I originally tried to do. One option I'm exploring now is reusing facebook's `prop-types` library. I see quite a few benefits: 

- It's been designed to typecheck objects _at runtime_, which is exactly what we need here
- it is battle tested
- a lot of developers are already using it, so that's a huge plus

There are some issues with `prop-types` API since it wasn't designed to work with anything else other than React  props, but I think there's a way around it. I'll let you know when I make it work

**Comment by koss-lebedev** [comment]
@ShMcK 
OK, I think this is ready for review. I finished the plugin, added tests and documentation. Please let me know what you think :)

**Comment by ShMcK** [comment]
This is really good. Great work.

I'm a bit worried about the package `ReactPropTypesSecret`, based on the constant names:

```
 __SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED: ReactDOM,
  __SECRET_DOM_SERVER_DO_NOT_USE_OR_YOU_WILL_BE_FIRED: ReactDOMServer,

**Comment by ShMcK** [comment]
Publishing as `@rematch/typings` may be confusing, as it sounds like a typescript or flow package.

Any recommendations for an alternate name?

**Comment by koss-lebedev** [comment]
That's a good point. I think we could use `typed-state` or `state-types` (kind of like `prop-types`), or maybe you have a better suggestion? Let me know and I'll submit a new PR with the updated names

**Comment by ShMcK** [comment]
`typed-state` sounds clearer to me. Also if you could change the folder name as well :)

Thanks again!

**Pull request merged**
