### PR TITLE
[typings] add in ModelReducers typing where bug occurs

### PR DESCRIPTION
**Pull request by andrewheekin**

### CODE REVIEW

**Comment by brunolemos** [comment]
@andrewheekin which bug are you referring to? Please open an issue with the minimal code necessary for reproduction.

**Comment by ShMcK** [comment]
@brunolemos is #412 a preferable fix to #410?

**Comment by brunolemos** [comment]
@ShMcK yes, this PR #410 break things, so it can't be merged

**Comment by ShMcK** [comment]
Will close in favor of recently merged #412

**Pull request closed without merging**
