### PR TITLE
Remove prettier parser option

### LINKED ISSUE #693: Don't pin parser to TypeScript for Prettier

### PR DESCRIPTION
**Pull request by imbsky**
Fixes #693

### CODE REVIEW

**Comment by imbsky** [comment]
All non-TypeScript files failed to format because the parser option was specified. This PR fixes the problem.

**Comment by imbsky** [comment]
This change ensures that code in Markdown, such as JavaScript, is formatted correctly.

**Comment by imbsky** [comment]
The build directory was included in the repository, so it was removed as well.

**Comment by ShMcK** [comment]
This is great, thanks @imbsky !

**Comment by imbsky** [comment]
👍

**Pull request merged**
