### PR TITLE
feature/subscribe-model-reducers-to-non-model-actions

### PR DESCRIPTION
**Pull request by blairbodnar**
As discussed in #322

### CODE REVIEW

**Comment by blairbodnar** [comment]
Wierd. All tests passed locally, not sure why `plugins/loading/test/loading-asBoolean.test.js` fails on travis. 🤔

**Comment by blairbodnar** [comment]
Ugh, and didn't realize `plugins/persist/package-lock.json` was out of sync for me and made it's way into this PR.

**Comment by blairbodnar** [comment]
... or don't bother with this, a nice middleware solution from @miickel solves it too. https://github.com/rematch/rematch/issues/322#issuecomment-378520145

**Comment by ShMcK** [comment]
I like @miickel's solution as well. Do you think we should move into core?

**Comment by blairbodnar** [comment]
Yeah, I think it'd be cool to have in core 👍🏻

**Comment by miickel** [comment]
One drawback with my solution is that subscriptions in `effects` won't work. But perhaps that is by design?

**Comment by blairbodnar** [comment]
Sorry for the delay on this one... Maybe we should just make @miickel's middleware solution https://github.com/rematch/rematch/issues/322#issuecomment-378520145 into a recipe?

**Comment by blairbodnar** [comment]
Closing this off, we can make this into a recipe instead. https://github.com/rematch/rematch/issues/322#issuecomment-378520145 Thanks!

**Pull request closed without merging**
