### PR TITLE
redux.rootReducers -  a hook at reducers base that returns next state

### LINKED ISSUE #168: Enhancers, Redux-Reset
Add Redux-Reset to persist plugin for resetting state.
https://github.com/wwayne/redux-reset

Redux-Persist can only purge local storage.

---

Will also require a "redux" enhancers API.

```js
redux: {
  enhancers: [enhancer1]
}
```

### PR DESCRIPTION
**Pull request by ShMcK**
References #177 & would close #168.

This PR so far only outlines the middleware with a failing test.

### CODE REVIEW

**Comment by ShMcK** [comment]
After looking into this, I realize redux middleware is not meant to change state. It can listen to actions, and manipulate those actions, but changes can only be made through reducers.

### Not a bug

In order to return a different state, you need to overwrite the "root reducer".

```js
const rootReducer = (state, action) => {
  // manipulate state here
  return appReducer(state, action)
}
```

We could create a hook in here on startup, and give it a potential name like `redux.rootReducerMiddleware`?

If `redux.rootReducerMiddleware` then wrap something in a `createRootReducer(combineReducers(state, action))` function, else use `combineReducers`.

### Use cases

Adding a state `reset`, such as on logout, that simply sets state to `undefined`, thereby taking the default reducer states.

Adding more powerful middleware that can manipulate the state, such as an optimized loading indicator plugin.

Somehow this PR became an issue...

**Comment by ShMcK** [comment]
### Proposal:

```ts
redux: {
   rootReducerWrapper?: (rootReducer: Reducer<any>) => (state: any, action: Action) => any,
}
```

### Implementation

```js
let rootReducer: Reducer<any> = mergeReducers()
if (redux.rootReducerWrapper) {
  rootReducer = redux.rootReducerWrapper(rootReducer)
}
```

Works as of last commit.

**Comment by ShMcK** [comment]
Changed the API to look like this:

```js
redux: {
  rootReducers: {
   'SAY_HI': (state, action) => 'HI'
    'RESET': () => undefined,
  }
}
```

That way it can handle multiple rootReducers, and looks similar to regular reducers.

**Comment by blairbodnar** [comment]
Very cool stuff @ShMcK ! I like it.

How about rather than returning `undefined`, the user has to explicitly set the state to the initial state. Perhaps changing the API to be like this:

```jsx
redux: {
  rootReducers: {
    'SAY_HI': (state, action, initialState) => 'HI',
    'RESET': (state, action, initialState) => ({ ...initialState }),
  }
}
```

What do you think? I could go either way, but I think I tend to lean this way because you can understand exactly what is going on when reading the line: 

`'RESET': (state, action, initialState) => ({ ...initialState }),`. 

When you read `'RESET': () => undefined` (without reading the docs), it might lead to confusion. Without reading the docs, one might interpret it as "Look like that sets the state to `undefined`"

Thoughts?

**Comment by ShMcK** [comment]
A couple things:

- I don't think this API would be used that often. Its kind of in the "danger zone unless you're resetting the state" place. 
- I originally tried to piece out the initialState from the models, and then find a way to return it. It was kind of tricky, and involved passing models into the redux init. Then I thought: "what if someone adds dynamic models, model(something)", then their state wouldn't be added.

**Comment by blairbodnar** [comment]
Good points...

For the second point, I was playing around this afternoon and got a version of it working with initialState as the third param. I will make a PR tomorrow if ya like? Or do you prefer we not go with that approach and keep it as the undefined will reset the state?

Also found a bug with this current PR and dynamic models:

1. init with a model
2. dynamically add another model `model({ ... })`
3. dispatch something that changes the state
4. dispatch a 'reset' (using the root reducer)
5. bug: the state isn't reset.

Hopefully that makes sense - sorry I'm in a rush and running out the door right now, will hopefully have some time tomorrow!

**Comment by ShMcK** [comment]
I'd like to see the version with initialState as the third param. I can only see people using initialState in one circumstance though, if they want to reset state. So adding it as a param wouldn't be too helpful.

For the bug, add a test and and we can work it out.

Awesome ideas! APIs always end up better with some discussion.

**Comment by blairbodnar** [comment]
Fixed the bug! :) 
https://github.com/rematch/rematch/pull/181/commits/af0356d30e2de45d15c208c282313c3d3be62bf7

**Pull request merged**
