### PR TITLE
WIP - Experimental types

### PR DESCRIPTION
**Pull request by ShMcK**
Ongoing from the work of @rtfpessoa.

This PR aims to refactor Rematch to use strict typings.

### CODE REVIEW

**Comment by ShMcK** [comment]
Some initial observations:

OOP has brought a lot of clarity to how things should be organized, and also made the typings very clear. You've also provided a clear way to provide a complete decoupling of stores.

I'll try to continue along this path to ensure tests pass, and the API remains consistent.

I can see a few additional feature possibilities thanks to the decoupling. It should be possible to have:
- multiple stores
- a global dispatch that can fire into multiple stores (though store.dispatch is still recommended)
- a way for stores to communicate with each other, if deemed necessary

@rtfpessoa feel free to continue, and thanks again for your contributions.

**Comment by ShMcK** [comment]
43 / 139 tests passing 👍

**Comment by nWidart** [comment]
I see the tsconfig file wasn't changed.

This could be added to it, to let typescript generate the type files.

```
"declaration": true
```

**Comment by nWidart** [comment]
👀 Can't wait for this to work so I can use in a typescript project :D 

I'm thinking a "quick fix" could be to not provide types, which makes it usable in typescript if I'm not mistaken.

**Comment by nWidart** [comment]
Hm, I'm not sure about that, possibly.

Though if there are no types at all, it could work. There are a lot of packages that don't provide types whatsoever, and it's still possible to use them in a typescript project.

However, if you're close to making this pull request work and that it'll make this package work with typescript projects, might not be worth it.

**Comment by ShMcK** [comment]
Agreed. I'll put my focus into this PR today before falling back to plan B - no types.

**Comment by resir014** [comment]
@ShMcK 

> Good call. Removing types and setting "declaration: true" would allow it to work in TS today?

CMIIW, but setting `declaration: true` will automatically generate a `.d.ts` file based on the types in your code, alongside your source file. You can then set `types` in your package.json to the generated types, in place of the custom typings.

I personally prefer having finer control over types with a custom `.d.ts` file over an automatically generated one, but your call!

**Comment by nWidart** [comment]
I checked out this branch inside my typescript project, and sadly I'm still getting the error on my model.

image

**Comment by yurifrl** [comment]
I seem to have the same issue here, changing ` export let dispatch: RematchDispatch` to ` export let dispatch: any` solves the issue for the time being

**Comment by yurifrl** [comment]
This also seam to work 
```
export type RematchDispatchLiteral = {
    [key: string]: {
        [key: string]: (action?: Action) => Promise<Dispatch<any>>
    }
}

export type RematchDispatchCall  = (any)

export type RematchDispatch = RematchDispatchCall | RematchDispatchLiteral
```

**Comment by nWidart** [comment]
Did you manage to override these types on your project without touching the package? 
That would be really nice, and allow us to use it now 😄

**Comment by yurifrl** [comment]
No, I'm editing the package, and considering using a fork for now, I had an approach where I ignore the compiler with an assertion like this: `(<any>dispatch).count.increment()` but this caused an other issue, that I isolated here: https://stackblitz.com/edit/rematch-angular-5-count-whit-type-error?file=app%2Fapp.component.ts

**Comment by yurifrl** [comment]
this seems to work `dispatch["count"]["increment"]()` with no refactor

**Comment by ShMcK** [comment]
Currently working off of the 1.0.0-alpha.0 branch. Finding a slower migration with passing tests to be favorable.

Ultimate goal is: 
- multiple stores
- TS support

**Comment by ShMcK** [comment]
close in favor of #240

**Pull request closed without merging**
