### PR TITLE
Keep isEffect tag

### PR DESCRIPTION
**Pull request by kostychev**
Fixes isEffect tag loss in loading plugin.

### CODE REVIEW

**Comment by semoal** [comment]
Hi, @kostychev could you provide some information about this pull request? 
What's the purpose? Is it a feature or a bug fix?

Thanks in advance.

**Comment by d3dc** [comment]
@semoal the `isEffect` tag is added by the core Effects plugin and used to watch for when to run side-effects. I haven't used the loading plugin to know the bug.

**Comment by semoal** [comment]
> @semoal the `isEffect` tag is added by the core Effects plugin and used to watch for when to run side-effects. I haven't used the loading plugin to know the bug.

I've used loading plugin in some project, but didn't find any issue related to this. That's why am i asking ^^

**Comment by byzyk** [comment]
I have stumbled upon the same issue recently.

I was working on a custom plugin where I had to rely on `isEffect` flag and there was an edge case: if the plugin is injected *after* the loading plugin like this `plugins: [loadingPlugin, myCustomPlugin]` - then `isEffect` flag in `myCustomPlugin` gets lost.

Came here to submit exactly the same PR but then found this one, I guess this should be merged in 👍🏽

**Comment by matepaiva** [comment]
"Came here to submit exactly the same PR but then found this one, I guess this should be merged in ". 

Please merge as soon as possible. It was very hard to identify this bug.

**Comment by semoal** [comment]
> "Came here to submit exactly the same PR but then found this one, I guess this should be merged in ".
> 
> Please merge as soon as possible. It was very hard to identify this bug.

it's already merged and probably already release on rematch 1.2.0

**Comment by matepaiva** [comment]
Oh, really. My fault, then. I will update my packages.

**Pull request merged**
