### PR TITLE
Select examples

### LINKED ISSUE #298: Cross-model actions/reducers?
I like what this library is trying to achieve. There is one thing that I couldn't grasp looking at the documentation / examples and code...

Say you have 2 models: A and B. You have some action defined in model A and you want a reducer in model B to listen to that action to mutate model's B state. How do you accomplish this?

This is useful for badges on the taskbar, handling auth actions (login / logout) where you want to clear and mutate state of non-auth related models, etc.

### PR DESCRIPTION
**Pull request by d3dc**
This updates the examples to use `@rematch/select` 2.0.0.

closes #298

I added a selector to the react/count example since it shows `connect`. I can take that commit out if it should remain simple. (or make a new example)

### CODE REVIEW

**Comment by ShMcK** [comment]
I think it may be easier for now to keep the count example as simple as possible. The idea of selectors can even be a bit of learning curve for those new to functional programming.

What do you think about moving a count-select example under `plugins/select/examples`?

**Comment by d3dc** [comment]
I went ahead and made a new example under select.
Should the ts example still have a selector then?

**Comment by ShMcK** [comment]
That's a good question. 

I might consider that the basic JS & TS examples to serve different purposes.

JS: shows how to make a basic app.
TS: shows an example of all kinds of typings. 

What are your thoughts?

**Comment by d3dc** [comment]
I don't think I'm the right crowd to have an opinion. I think I agree with you that TS is more about showing how types are dealt with. An example of a working TS project is one where it compiles with hints.

I have been thinking about the todo example I made in a codesandbox, and wondering if it might adapt well for #390; but thats not here nor there for this chain of issues.

**Comment by ShMcK** [comment]
Your todos complex example may be better linked to in a codesandbox on the README under the examples section. 

Let me know when you think this PR is ready :)

**Comment by d3dc** [comment]
I just tested running it. I guess I thought it wasn't obvious that you could remove things. If the example is sound then, it should be good.

**Pull request merged**
