### PR TITLE
Add hooks docs and example

### PR DESCRIPTION
**Pull request by koss-lebedev**
The latest release of `react-redux 7.1.0` adds support for hooks, so I think it'd be helpful to see that Rematch can be used with hooks as well. This PR adds documentation and example application of using Rematch with hooks.

### CODE REVIEW

**Comment by d3dc** [comment]
Note to future packages: name hooks gooder. 😁

```js
const select = useSelect()
const selected = useSelector(select.selection.selected)
```

**Comment by JiangWeixian** [comment]
any usestore hooks docs and example?

**Comment by koss-lebedev** [comment]
@JiangWeixian `useStore` hook has very low applicability, and in most cases `useSelector` hook should be used instead. (according to Redux docs: https://react-redux.js.org/next/api/hooks#usestore)

**Comment by JiangWeixian** [comment]
@koss-lebedev 

i update react-redux@7.1.0 @types/react-redux@7.1.0。there are some ts type errors

```ts
Type 'Dispatch<Action<any>>' is not assignable to type 'ExtractRematchDispatchersFromModels<Models & { global: { state: GlobalState; reducers: { _setOperators(state: GlobalState, { operators }: any): { operators: any; me?: Operator | undefined; }; _setMe(state: GlobalState, { me }: any): { ...; }; }; effects: { ...; }; }; ... 49 more ...; userDevice: { ...; }; }> & ((act...'.
```

......................

**Comment by JiangWeixian** [comment]
@koss-lebedev  a little advice

i think you should add hook folder into `test/typescript.test.ts` files

```js
const { check } = require('typings-tester')

const tsDirectory = 'examples/ts'
const examples = ['count', 'hook']

describe('typings', () => {
	for (const example of examples) {
		test(`should compile and run "${tsDirectory}/${example}" without error`, async () => {
			expect(() =>
				check(
					[`./${tsDirectory}/${example}/src/index.tsx`],
					`./${tsDirectory}/${example}/tsconfig.json`
				)
			).not.toThrow()
		})
	}
})
```

**Comment by d3dc** [comment]
@koss-lebedev re: `useStore()`, what are your thoughts on a pattern such as:
```js
  const { select, dispatch } = useStore()

  const selection = useSelector(
    select({
      size: it.topology.size,
      border: select.topology?.fromBorder(it.country),
    })
  )

  const actions = {
    focused: dispatch.mapFocus?.focused,
    dragged: dispatch.mapFocus?.dragged,
  }
```

**Comment by semoal** [comment]
Check conflicts mate we’ll merge it @koss-lebedev

**Comment by ShMcK** [comment]
@koss-lebedev 
Would love to merge this update in, any chance we can get a conflict resolution on the docs/purpose.md ?

**Comment by koss-lebedev** [comment]
@semoal @ShMcK thanks, I fixed the conflict

**Pull request merged**
