### PR TITLE
A simpler example

### PR DESCRIPTION
**Pull request by g3r4n**
As highlighted in steps 3 we can use dispatch to make the example simpler

### CODE REVIEW

**Comment by ShMcK** [comment]
Good point. 

There are two goals to the example:
1) show a simple demo
2) show people how `dispatch`, `reducers` and `effects` work.

If we remove params from the example, users might not understand how to pass "payload" around.

**Comment by g3r4n** [comment]
I didn’t change the steps 3 where there is an example about payload.
Should I correct something or close the PR ?

**Comment by blairbodnar** [comment]
Thanks @g3r4n , It's funny - I debated a lot on this when we were doing those examples! In fact, I think we previously showed it the way you do here!

I personally like to use the `mapDispatchToProps` approach because it keeps the component totally isolated from rematch - It relies only on it's own props.

However, I do know that people like to pass the global dispatch directly like the PR suggests too!

Hmm, I'm torn. One one hand, it feels best practice-y to me to have the component pure... but on the other hand there is less code which shows off rematch's global dispatch. 

That being said, do you still feel the PR is the way to go?

**Comment by g3r4n** [comment]
I' closing the PR because steps 1, 2, 3 and the example are showing different ways to work with this API. This PR will not bring more value than the current state.

**Comment by ShMcK** [comment]
Thanks @g3r4n. I appreciate the PR, and certainly agree that your example is much simpler. Hopefully we can include easier ways to reduce boilerplate in a tutorial series for Rematch in the near future :)

**Comment by blairbodnar** [comment]
Ditto, thanks @g3r4n !

**Pull request closed without merging**
