### PR TITLE
feat(effectPromiseValue): promises returned from effects resolve to the return value

### PR DESCRIPTION
**Pull request by pierissimo**
as discussed:
https://github.com/rematch/rematch/issues/208

### CODE REVIEW

**Comment by ShMcK** [comment]
I guess it was as simple as that. My mistake, I had added storeDispatch elsewhere.

Nice work!

**Comment by ShMcK** [comment]
closes #208.

Released as @rematch/core v0.3.0

**Comment by pierissimo** [comment]
Thanks

**Comment by blairbodnar** [comment]
Awesome, nice work @pierissimo !

**Comment by pierissimo** [comment]
no problem, I really like the project!

**Comment by pierissimo** [comment]
I may have a few ideas about features/code that I could show you in the next few days if that's not a problem!

**Pull request merged**
