### PR TITLE
fix(loadingEffectReturnValuePropagation): Propagate effect return value

### PR DESCRIPTION
**Pull request by eeynard**
Fix loading plugin regression regarding the issue #208

### CODE REVIEW

**Comment by ShMcK** [comment]
Good catch, just one small change and should be ready to merge :)

**Comment by eeynard** [comment]
Great ! Do you know when you will be able to merge and release the fix ?

**Comment by ShMcK** [comment]
Sorry, I hadn't submitted the change request. But can merge right after :)

**Comment by eeynard** [comment]
Oh yes you're right ! I just fixed it, sorry for the typo :)

**Comment by eeynard** [comment]
@ShMcK I tried the v1.0.2 of the loading plugin and it does not seem to work. I checked the map files and it seems that the fix had not been packaged with the new release. Can't find the piece of code, any idea ?

**Comment by ShMcK** [comment]
I must not have run build before publishing... my mistake.

**Comment by eeynard** [comment]
It works with v1.0.3 ! Thanks

**Comment by scientist1642** [comment]
Hmm, still Promise problem in `Loading 1.0.3` and `@rematch/core": "1.0.0-alpha.4"`, For me. 
If I remove Loading I can handle promises fine.

**Pull request merged**
